### ISSUE TITLE
Tag cloud is not related to the article content

### ISSUE THREAD

**Issue by tomaslibal** [unruly/unruly.github.io#5]
Steps to reproduce:

1) navigate to http://tech.unruly.co/blog/2015/10/05/object-util.html
2) see the tag cloud below the article, including tags "site", "java" on an article about JavaScript and VAST parser.

Conversely, the tags specified in the blog post are pushed to tag cloud on other article pages. Maybe we should separate them so that they do not appear to be closely related to the article but rather the whole page.

**Comment by jahed** [comment]
Fixed. We were listing all tags under articles instead of just that article's tags.

Here's the change:
https://github.com/unruly/unruly.github.io/commit/1f378fc1caa3860d5f5a138f5931d26c289c9a0b
