### ISSUE TITLE
`bundle install` fails due to middleman-deploy's version "2.0.0-alpha"

### ISSUE THREAD

**Issue by tomaslibal** [unruly/unruly.github.io#6]
Steps to reproduce:

```
tomas@tlmp:~/workspace/$ git clone <repo> @ bf5658327a20057f997896134b3a827c1757c3e1
tomas@tlmp:~/workspace/unruly.github.io$ gem install bundler
tomas@tlmp:~/workspace/unruly.github.io$ bundle install
Fetching git://github.com/middleman-contrib/middleman-deploy.git
There was a ArgumentError while loading middleman-deploy.gemspec: 
Malformed version number string 2.0.0-alpha from
/home/tomas/.bundler/ruby/1.9.1/middleman-deploy-243ab38b0889/middleman-deploy.gemspec:8:in
`block in <main>'
```

I guess this is because the Gemfile points to the master of the middleman-deploy's git repository and this has a version '2.0.0-alpha' which seems to break the bundler.

Can be fixed updating Gemfile:8 to: `gem 'middleman-deploy', github: 'middleman-contrib/middleman-deploy', ref: '9cd8988a66829550fcbfbb90e306593d6ee9307d`

**Comment by jahed** [comment]
Fix was fixed after future `middleman-deploy` releases.
